title: "ChamaneTaiba"
tagline: "اسلامی شاعری اور نعتیہ مجموعہ"
lang: ur
direction: rtl
baseurl: ""
url: "https://your-username.github.io"  # later change karna

# Jekyll settings
markdown: kramdown
permalink: /:categories/:title/
